name: "ðŸ“š latest Blog"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */24 * * *" # Runs Every 24 Hours

jobs:
  update_blogs:
    name: "Update With Latest Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "ðŸ“¥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "ðŸ“š DEV Updater"
        uses: "ndrohith09/action-hashnode-blog@1.1.1"
        with:
          USERNAME: "Rohith ND" # Hashnode Username
          COUNT: 4 # MAX Visisble
          STYLE: "blog-left"
          BLOG_URL: "https://dev.to/ndrohith09/"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

